### ISSUE TITLE
searchが増えてく

### ISSUE THREAD

**Issue by sasayaka** [hmitani-aiit/study_plan#53]
![serch増える](https://user-images.githubusercontent.com/49612816/63161494-30839f00-c05b-11e9-80a9-3328825cd461.JPG)

ライブラリがいまいちなので、こっちで直さないといけないみたい

**Comment by uganikov** [comment]
-  戻る -> 進む
 ブラウザの bfcache により初期化済み状態でページの準備が完了する。そこに ready ハンドラで再初期化するためこのような状況となる。 ready ではなく onload を使うとこのパターンでははんどらが呼ばれなくなるため解決
- ページ遷移 -> 戻る
 rails の turbolink により、逆に onload ではなく ready ハンドラしか効かないため、上記を直すとこちらが壊れる。lectures ページの turbolink を無効化して対応する。
